# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 12 Sep 2014 14:22:25 +0000
*	@ALL	1
start	@ALL	1
suggest	@ALL	2
todo	@ALL	1
