# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 09 Sep 2014 01:54:06 +0000
*               @ALL          1
*               @user         8
