<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 09 Sep 2014 01:54:06 +0000
 */
$conf['title'] = 'CSEWiki';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-nc-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
