<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Fri, 19 Sep 2014 19:32:11 +0000
 */

$conf['title'] = 'CSEWiki';
$conf['template'] = 'csewikitpl';
$conf['license'] = 'cc-by-sa';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['tocminheads'] = '4';
$conf['maxtoclevel'] = '4';
$conf['maxseclevel'] = '2';
$conf['camelcase'] = 1;
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['passcrypt'] = 'sha512';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['htmlmail'] = 0;
$conf['useslash'] = 1;
$conf['tpl']['csewikitpl']['bootswatch'] = 'cosmo';

// end auto-generated content
