<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Thu, 18 Sep 2014 16:29:20 +0000
 */

$conf['title'] = 'CSEWiki';
$conf['template'] = 'csewikitpl';
$conf['license'] = 'cc-by-sa';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['useacl'] = 1;
$conf['passcrypt'] = 'sha1';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlmail'] = 0;
$conf['tpl']['csewikitpl']['bootswatch'] = 'slate';

// end auto-generated content
